namespace JMayer.Net.ProtocolDataUnit;

/// <summary>
/// The class represents a protocol data unit that was parsed from the stream but the data is wrong.
/// </summary>
public sealed class ErroneousPDU
{
    /// <summary>
    /// The property gets the binary format for the message.
    /// </summary>
    public byte[] BinaryFormat { get; private init; }

    /// <summary>
    /// The property gets the exception generated by the parser.
    /// </summary>
    public Exception Exception { get; private init; }

    /// <summary>
    /// The property gets the string format for the message.
    /// </summary>
    /// <remarks>
    /// Not all protocols will have a string representation of the message.
    /// </remarks>
    public string StringFormat { get; private init; }

    /// <summary>
    /// The property constructor.
    /// </summary>
    /// <param name="binaryFormat">The binary format for the message.</param>
    /// <param name="exception">The exception generated by the parser.</param>
    /// <param name="stringFormat">The string format for the message.</param>
    public ErroneousPDU(byte[] binaryFormat, Exception exception, string stringFormat)
    {
        BinaryFormat = binaryFormat;
        Exception = exception;
        StringFormat = stringFormat;
    }
}
